import Foundation

struct StationProvider {
    static let allStations: [Station] = shanghaiStations
    
    static let beijingStations: [Station] = []
    
    static let shanghaiStations: [Station] = [
        // 1号线
        Station(name: "莘庄", nameEn: "Xinzhuang", line: "1号线", city: "上海"),
        Station(name: "外环路", nameEn: "Waihuan Road", line: "1号线", city: "上海"),
        Station(name: "莲花路", nameEn: "Lianhua Road", line: "1号线", city: "上海"),
        Station(name: "锦江乐园", nameEn: "Jinjiang Park", line: "1号线", city: "上海"),
        Station(name: "上海南站", nameEn: "Shanghai South Railway Station", line: "1号线", city: "上海"),
        Station(name: "漕宝路", nameEn: "Caobao Road", line: "1号线", city: "上海"),
        Station(name: "上海体育馆", nameEn: "Shanghai Indoor Stadium", line: "1号线", city: "上海"),
        Station(name: "徐家汇", nameEn: "Xujiahui", line: "1号线", city: "上海"),
        Station(name: "衡山路", nameEn: "Hengshan Road", line: "1号线", city: "上海"),
        Station(name: "常熟路", nameEn: "Changshu Road", line: "1号线", city: "上海"),
        Station(name: "陕西南路", nameEn: "South Shaanxi Road", line: "1号线", city: "上海"),
        Station(name: "一大会址·黄陂南路", nameEn: "Site of the First CPC National Congress · South Huangpi Road", line: "1号线", city: "上海"),
        Station(name: "人民广场", nameEn: "People's Square", line: "1号线", city: "上海"),
        Station(name: "新闸路", nameEn: "Xinzha Road", line: "1号线", city: "上海"),
        Station(name: "汉中路", nameEn: "Hanzhong Road", line: "1号线", city: "上海"),
        Station(name: "上海火车站", nameEn: "Shanghai Railway Station", line: "1号线", city: "上海"),
        Station(name: "中山北路", nameEn: "North Zhongshan Road", line: "1号线", city: "上海"),
        Station(name: "延长路", nameEn: "Yanchang Road", line: "1号线", city: "上海"),
        Station(name: "上海马戏城", nameEn: "Shanghai Circus World", line: "1号线", city: "上海"),
        Station(name: "汶水路", nameEn: "Wenshui Road", line: "1号线", city: "上海"),
        Station(name: "彭浦新村", nameEn: "Pengpu Xincun", line: "1号线", city: "上海"),
        Station(name: "共康路", nameEn: "Gongkang Road", line: "1号线", city: "上海"),
        Station(name: "通河新村", nameEn: "Tonghe Xincun", line: "1号线", city: "上海"),
        Station(name: "呼兰路", nameEn: "Hulan Road", line: "1号线", city: "上海"),
        Station(name: "共富新村", nameEn: "Gongfu Xincun", line: "1号线", city: "上海"),
        Station(name: "宝安公路", nameEn: "Bao'an Highway", line: "1号线", city: "上海"),
        Station(name: "友谊西路", nameEn: "West Youyi Road", line: "1号线", city: "上海"),
        Station(name: "富锦路", nameEn: "Fujin Road", line: "1号线", city: "上海"),

        // 2号线
        Station(name: "国家会展中心", nameEn: "National Exhibition and Convention Center", line: "2号线", city: "上海"),
        Station(name: "虹桥火车站", nameEn: "Hongqiao Railway Station", line: "2号线", city: "上海"),
        Station(name: "虹桥2号航站楼", nameEn: "Hongqiao Airport Terminal 2", line: "2号线", city: "上海"),
        Station(name: "淞虹路", nameEn: "Songhong Road", line: "2号线", city: "上海"),
        Station(name: "北新泾", nameEn: "Beixinjing", line: "2号线", city: "上海"),
        Station(name: "威宁路", nameEn: "Weining Road", line: "2号线", city: "上海"),
        Station(name: "娄山关路", nameEn: "Loushanguan Road", line: "2号线", city: "上海"),
        Station(name: "中山公园", nameEn: "Zhongshan Park", line: "2号线", city: "上海"),
        Station(name: "江苏路", nameEn: "Jiangsu Road", line: "2号线", city: "上海"),
        Station(name: "静安寺", nameEn: "Jing'an Temple", line: "2号线", city: "上海"),
        Station(name: "南京西路", nameEn: "West Nanjing Road", line: "2号线", city: "上海"),
        Station(name: "人民广场", nameEn: "People's Square", line: "2号线", city: "上海"),
        Station(name: "南京东路", nameEn: "East Nanjing Road", line: "2号线", city: "上海"),
        Station(name: "陆家嘴", nameEn: "Lujiazui", line: "2号线", city: "上海"),
        Station(name: "浦东南路", nameEn: "South Pudong Road", line: "2号线", city: "上海"),
        Station(name: "世纪大道", nameEn: "Century Avenue", line: "2号线", city: "上海"),
        Station(name: "上海科技馆", nameEn: "Shanghai Science and Technology Museum", line: "2号线", city: "上海"),
        Station(name: "世纪公园", nameEn: "Century Park", line: "2号线", city: "上海"),
        Station(name: "龙阳路", nameEn: "Longyang Road", line: "2号线", city: "上海"),
        Station(name: "张江高科", nameEn: "Zhangjiang High Technology Park", line: "2号线", city: "上海"),
        Station(name: "金科路", nameEn: "Jinke Road", line: "2号线", city: "上海"),
        Station(name: "广兰路", nameEn: "Guanglan Road", line: "2号线", city: "上海"),
        Station(name: "唐镇", nameEn: "Tangzhen", line: "2号线", city: "上海"),
        Station(name: "创新中路", nameEn: "Middle Chuangxin Road", line: "2号线", city: "上海"),
        Station(name: "华夏东路", nameEn: "East Huaxia Road", line: "2号线", city: "上海"),
        Station(name: "川沙", nameEn: "Chuansha", line: "2号线", city: "上海"),
        Station(name: "凌空路", nameEn: "Lingkong Road", line: "2号线", city: "上海"),
        Station(name: "远东大道", nameEn: "Yuandong Avenue", line: "2号线", city: "上海"),
        Station(name: "海天三路", nameEn: "Haitian 3rd Road", line: "2号线", city: "上海"),
        Station(name: "浦东国际机场", nameEn: "Pudong International Airport", line: "2号线", city: "上海"),

        // 3号线
        Station(name: "上海南站", nameEn: "Shanghai South Railway Station", line: "3号线", city: "上海"),
        Station(name: "石龙路", nameEn: "Shilong Road", line: "3号线", city: "上海"),
        Station(name: "龙漕路", nameEn: "Longcao Road", line: "3号线", city: "上海"),
        Station(name: "漕溪路", nameEn: "Caoxi Road", line: "3号线", city: "上海"),
        Station(name: "宜山路", nameEn: "Yishan Road", line: "3号线", city: "上海"),
        Station(name: "虹桥路", nameEn: "Hongqiao Road", line: "3号线", city: "上海"),
        Station(name: "延安西路", nameEn: "West Yan'an Road", line: "3号线", city: "上海"),
        Station(name: "中山公园", nameEn: "Zhongshan Park", line: "3号线", city: "上海"),
        Station(name: "金沙江路", nameEn: "Jinshajiang Road", line: "3号线", city: "上海"),
        Station(name: "曹杨路", nameEn: "Caoyang Road", line: "3号线", city: "上海"),
        Station(name: "镇坪路", nameEn: "Zhenping Road", line: "3号线", city: "上海"),
        Station(name: "中潭路", nameEn: "Zhongtan Road", line: "3号线", city: "上海"),
        Station(name: "上海火车站", nameEn: "Shanghai Railway Station", line: "3号线", city: "上海"),
        Station(name: "宝山路", nameEn: "Baoshan Road", line: "3号线", city: "上海"),
        Station(name: "东宝兴路", nameEn: "Dongbaoxing Road", line: "3号线", city: "上海"),
        Station(name: "虹口足球场", nameEn: "Hongkou Football Stadium", line: "3号线", city: "上海"),
        Station(name: "赤峰路", nameEn: "Chifeng Road", line: "3号线", city: "上海"),
        Station(name: "大柏树", nameEn: "Dabaishu", line: "3号线", city: "上海"),
        Station(name: "江湾镇", nameEn: "Jiangwan Town", line: "3号线", city: "上海"),
        Station(name: "殷高西路", nameEn: "West Yingao Road", line: "3号线", city: "上海"),
        Station(name: "长江南路", nameEn: "South Changjiang Road", line: "3号线", city: "上海"),
        Station(name: "淞发路", nameEn: "Songfa Road", line: "3号线", city: "上海"),
        Station(name: "张华浜", nameEn: "Zhanghuabang", line: "3号线", city: "上海"),
        Station(name: "淞滨路", nameEn: "Songbin Road", line: "3号线", city: "上海"),
        Station(name: "水产路", nameEn: "Shuichan Road", line: "3号线", city: "上海"),
        Station(name: "宝杨路", nameEn: "Baoyang Road", line: "3号线", city: "上海"),
        Station(name: "友谊路", nameEn: "Youyi Road", line: "3号线", city: "上海"),
        Station(name: "铁力路", nameEn: "Tieli Road", line: "3号线", city: "上海"),
        Station(name: "江杨北路", nameEn: "North Jiangyang Road", line: "3号线", city: "上海"),

        // 4号线
        Station(name: "宜山路", nameEn: "Yishan Road", line: "4号线", city: "上海"),
        Station(name: "虹桥路", nameEn: "Hongqiao Road", line: "4号线", city: "上海"),
        Station(name: "延安西路", nameEn: "West Yan'an Road", line: "4号线", city: "上海"),
        Station(name: "中山公园", nameEn: "Zhongshan Park", line: "4号线", city: "上海"),
        Station(name: "金沙江路", nameEn: "Jinshajiang Road", line: "4号线", city: "上海"),
        Station(name: "曹杨路", nameEn: "Caoyang Road", line: "4号线", city: "上海"),
        Station(name: "镇坪路", nameEn: "Zhenping Road", line: "4号线", city: "上海"),
        Station(name: "中潭路", nameEn: "Zhongtan Road", line: "4号线", city: "上海"),
        Station(name: "上海火车站", nameEn: "Shanghai Railway Station", line: "4号线", city: "上海"),
        Station(name: "宝山路", nameEn: "Baoshan Road", line: "4号线", city: "上海"),
        Station(name: "海伦路", nameEn: "Hailun Road", line: "4号线", city: "上海"),
        Station(name: "临平路", nameEn: "Linping Road", line: "4号线", city: "上海"),
        Station(name: "大连路", nameEn: "Dalian Road", line: "4号线", city: "上海"),
        Station(name: "杨树浦路", nameEn: "Yangshupu Road", line: "4号线", city: "上海"),
        Station(name: "浦东大道", nameEn: "Pudong Avenue", line: "4号线", city: "上海"),
        Station(name: "世纪大道", nameEn: "Century Avenue", line: "4号线", city: "上海"),
        Station(name: "浦电路", nameEn: "Pudian Road", line: "4号线", city: "上海"),
        Station(name: "蓝村路", nameEn: "Lancun Road", line: "4号线", city: "上海"),
        Station(name: "塘桥", nameEn: "Tangqiao", line: "4号线", city: "上海"),
        Station(name: "南浦大桥", nameEn: "Nanpu Bridge", line: "4号线", city: "上海"),
        Station(name: "西藏南路", nameEn: "South Xizang Road", line: "4号线", city: "上海"),
        Station(name: "鲁班路", nameEn: "Luban Road", line: "4号线", city: "上海"),
        Station(name: "大木桥路", nameEn: "Damuqiao Road", line: "4号线", city: "上海"),
        Station(name: "东安路", nameEn: "Dong'an Road", line: "4号线", city: "上海"),
        Station(name: "上海体育场", nameEn: "Shanghai Stadium", line: "4号线", city: "上海"),
        Station(name: "上海体育馆", nameEn: "Shanghai Indoor Stadium", line: "4号线", city: "上海"),

        // 5号线
        Station(name: "莘庄", nameEn: "Xinzhuang", line: "5号线", city: "上海"),
        Station(name: "春申路", nameEn: "Chunshen Road", line: "5号线", city: "上海"),
        Station(name: "银都路", nameEn: "Yindu Road", line: "5号线", city: "上海"),
        Station(name: "颛桥", nameEn: "Zhuanqiao", line: "5号线", city: "上海"),
        Station(name: "北桥", nameEn: "Beiqiao", line: "5号线", city: "上海"),
        Station(name: "剑川路", nameEn: "Jianchuan Road", line: "5号线", city: "上海"),
        Station(name: "东川路", nameEn: "Dongchuan Road", line: "5号线", city: "上海"),
        Station(name: "江川路", nameEn: "Jiangchuan Road", line: "5号线", city: "上海"),
        Station(name: "西渡", nameEn: "Xidu", line: "5号线", city: "上海"),
        Station(name: "萧塘", nameEn: "Xiaotang", line: "5号线", city: "上海"),
        Station(name: "奉浦大道", nameEn: "Fengpu Avenue", line: "5号线", city: "上海"),
        Station(name: "环城东路", nameEn: "Huancheng Road East", line: "5号线", city: "上海"),
        Station(name: "望园路", nameEn: "Wangyuan Road", line: "5号线", city: "上海"),
        Station(name: "金海湖", nameEn: "Jinhai Lake", line: "5号线", city: "上海"),
        Station(name: "奉贤新城", nameEn: "Fengxian Xincheng", line: "5号线", city: "上海"),

        // 7号线
        Station(name: "美兰湖", nameEn: "Meilan Lake", line: "7号线", city: "上海"),
        Station(name: "罗南新村", nameEn: "Luonan Xincun", line: "7号线", city: "上海"),
        Station(name: "潘广路", nameEn: "Panguang Road", line: "7号线", city: "上海"),
        Station(name: "刘行", nameEn: "Liuhang", line: "7号线", city: "上海"),
        Station(name: "顾村公园", nameEn: "Gucun Park", line: "7号线", city: "上海"),
        Station(name: "祁华路", nameEn: "Qihua Road", line: "7号线", city: "上海"),
        Station(name: "上海大学", nameEn: "Shanghai University", line: "7号线", city: "上海"),
        Station(name: "南陈路", nameEn: "Nanchen Road", line: "7号线", city: "上海"),
        Station(name: "上大路", nameEn: "Shangda Road", line: "7号线", city: "上海"),
        Station(name: "场中路", nameEn: "Changzhong Road", line: "7号线", city: "上海"),
        Station(name: "大场镇", nameEn: "Dachang Town", line: "7号线", city: "上海"),
        Station(name: "行知路", nameEn: "Xingzhi Road", line: "7号线", city: "上海"),
        Station(name: "大华三路", nameEn: "Dahua 3rd Road", line: "7号线", city: "上海"),
        Station(name: "新村路", nameEn: "Xincun Road", line: "7号线", city: "上海"),
        Station(name: "岚皋路", nameEn: "Langao Road", line: "7号线", city: "上海"),
        Station(name: "镇坪路", nameEn: "Zhenping Road", line: "7号线", city: "上海"),
        Station(name: "长寿路", nameEn: "Changshou Road", line: "7号线", city: "上海"),
        Station(name: "昌平路", nameEn: "Changping Road", line: "7号线", city: "上海"),
        Station(name: "静安寺", nameEn: "Jing'an Temple", line: "7号线", city: "上海"),
        Station(name: "常熟路", nameEn: "Changshu Road", line: "7号线", city: "上海"),
        Station(name: "肇嘉浜路", nameEn: "Zhaojiabang Road", line: "7号线", city: "上海"),
        Station(name: "东安路", nameEn: "Dong'an Road", line: "7号线", city: "上海"),
        Station(name: "龙华中路", nameEn: "Middle Longhua Road", line: "7号线", city: "上海"),
        Station(name: "后滩", nameEn: "Houtan", line: "7号线", city: "上海"),
        Station(name: "长清路", nameEn: "Changqing Road", line: "7号线", city: "上海"),
        Station(name: "耀华路", nameEn: "Yaohua Road", line: "7号线", city: "上海"),
        Station(name: "云台路", nameEn: "Yuntai Road", line: "7号线", city: "上海"),
        Station(name: "高科西路", nameEn: "West Gaoke Road", line: "7号线", city: "上海"),
        Station(name: "杨高南路", nameEn: "South Yanggao Road", line: "7号线", city: "上海"),
        Station(name: "锦绣路", nameEn: "Jinxiu Road", line: "7号线", city: "上海"),
        Station(name: "芳华路", nameEn: "Fanghua Road", line: "7号线", city: "上海"),
        Station(name: "龙阳路", nameEn: "Longyang Road", line: "7号线", city: "上海"),
        Station(name: "花木路", nameEn: "Huamu Road", line: "7号线", city: "上海"),

        // 8号线
        Station(name: "市光路", nameEn: "Shiguang Road", line: "8号线", city: "上海"),
        Station(name: "嫩江路", nameEn: "Nenjiang Road", line: "8号线", city: "上海"),
        Station(name: "翔殷路", nameEn: "Xiangyin Road", line: "8号线", city: "上海"),
        Station(name: "黄兴公园", nameEn: "Huangxing Park", line: "8号线", city: "上海"),
        Station(name: "延吉中路", nameEn: "Middle Yanji Road", line: "8号线", city: "上海"),
        Station(name: "黄兴路", nameEn: "Huangxing Road", line: "8号线", city: "上海"),
        Station(name: "江浦路", nameEn: "Jiangpu Road", line: "8号线", city: "上海"),
        Station(name: "鞍山新村", nameEn: "Anshan Xincun", line: "8号线", city: "上海"),
        Station(name: "四平路", nameEn: "Siping Road", line: "8号线", city: "上海"),
        Station(name: "曲阳路", nameEn: "Quyang Road", line: "8号线", city: "上海"),
        Station(name: "虹口足球场", nameEn: "Hongkou Football Stadium", line: "8号线", city: "上海"),
        Station(name: "西藏北路", nameEn: "North Xizang Road", line: "8号线", city: "上海"),
        Station(name: "中兴路", nameEn: "Zhongxing Road", line: "8号线", city: "上海"),
        Station(name: "曲阜路", nameEn: "Qufu Road", line: "8号线", city: "上海"),
        Station(name: "人民广场", nameEn: "People's Square", line: "8号线", city: "上海"),
        Station(name: "大世界", nameEn: "Dashijie", line: "8号线", city: "上海"),
        Station(name: "老西门", nameEn: "Laoximen", line: "8号线", city: "上海"),
        Station(name: "陆家浜路", nameEn: "Lujiabang Road", line: "8号线", city: "上海"),
        Station(name: "西藏南路", nameEn: "South Xizang Road", line: "8号线", city: "上海"),
        Station(name: "中华艺术宫", nameEn: "China Art Museum", line: "8号线", city: "上海"),
        Station(name: "耀华路", nameEn: "Yaohua Road", line: "8号线", city: "上海"),
        Station(name: "成山路", nameEn: "Chengshan Road", line: "8号线", city: "上海"),
        Station(name: "杨思", nameEn: "Yangsi", line: "8号线", city: "上海"),
        Station(name: "东方体育中心", nameEn: "Oriental Sports Center", line: "8号线", city: "上海"),
        Station(name: "凌兆新村", nameEn: "Lingzhao Xincun", line: "8号线", city: "上海"),
        Station(name: "芦恒路", nameEn: "Luheng Road", line: "8号线", city: "上海"),
        Station(name: "浦江镇", nameEn: "Pujiang Town", line: "8号线", city: "上海"),
        Station(name: "江月路", nameEn: "Jiangyue Road", line: "8号线", city: "上海"),
        Station(name: "联航路", nameEn: "Lianhang Road", line: "8号线", city: "上海"),
        Station(name: "沈杜公路", nameEn: "Shendu Highway", line: "8号线", city: "上海"),

        // 9号线
        Station(name: "上海松江站", nameEn: "Shanghai Songjiang Railway Station", line: "9号线", city: "上海"),
        Station(name: "醉白池", nameEn: "Zuibaichi", line: "9号线", city: "上海"),
        Station(name: "松江体育中心", nameEn: "Songjiang Sports Center", line: "9号线", city: "上海"),
        Station(name: "松江新城", nameEn: "Songjiang Xincheng", line: "9号线", city: "上海"),
        Station(name: "松江大学城", nameEn: "Songjiang University Town", line: "9号线", city: "上海"),
        Station(name: "洞泾", nameEn: "Dongjing", line: "9号线", city: "上海"),
        Station(name: "佘山", nameEn: "Sheshan", line: "9号线", city: "上海"),
        Station(name: "泗泾", nameEn: "Sijing", line: "9号线", city: "上海"),
        Station(name: "九亭", nameEn: "Jiuting", line: "9号线", city: "上海"),
        Station(name: "中春路", nameEn: "Zhongchun Road", line: "9号线", city: "上海"),
        Station(name: "七宝", nameEn: "Qibao", line: "9号线", city: "上海"),
        Station(name: "星中路", nameEn: "Xingzhong Road", line: "9号线", city: "上海"),
        Station(name: "合川路", nameEn: "Hechuan Road", line: "9号线", city: "上海"),
        Station(name: "漕河泾开发区", nameEn: "Caohejing Hi-Tech Park", line: "9号线", city: "上海"),
        Station(name: "桂林路", nameEn: "Guilin Road", line: "9号线", city: "上海"),
        Station(name: "宜山路", nameEn: "Yishan Road", line: "9号线", city: "上海"),
        Station(name: "徐家汇", nameEn: "Xujiahui", line: "9号线", city: "上海"),
        Station(name: "肇嘉浜路", nameEn: "Zhaojiabang Road", line: "9号线", city: "上海"),
        Station(name: "嘉善路", nameEn: "Jiashan Road", line: "9号线", city: "上海"),
        Station(name: "打浦桥", nameEn: "Dapuqiao", line: "9号线", city: "上海"),
        Station(name: "马当路", nameEn: "Madang Road", line: "9号线", city: "上海"),
        Station(name: "陆家浜路", nameEn: "Lujiabang Road", line: "9号线", city: "上海"),
        Station(name: "小南门", nameEn: "Xiaonanmen", line: "9号线", city: "上海"),
        Station(name: "商城路", nameEn: "Shangcheng Road", line: "9号线", city: "上海"),
        Station(name: "世纪大道", nameEn: "Century Avenue", line: "9号线", city: "上海"),
        Station(name: "杨高中路", nameEn: "Middle Yanggao Road", line: "9号线", city: "上海"),
        Station(name: "芳甸路", nameEn: "Fangdian Road", line: "9号线", city: "上海"),
        Station(name: "蓝天路", nameEn: "Lantian Road", line: "9号线", city: "上海"),
        Station(name: "台儿庄路", nameEn: "Ta'erzhuang Road", line: "9号线", city: "上海"),
        Station(name: "金桥", nameEn: "Jinqiao", line: "9号线", city: "上海"),
        Station(name: "金吉路", nameEn: "Jinji Road", line: "9号线", city: "上海"),
        Station(name: "金海路", nameEn: "Jinhai Road", line: "9号线", city: "上海"),
        Station(name: "顾唐路", nameEn: "Gutang Road", line: "9号线", city: "上海"),
        Station(name: "民雷路", nameEn: "Minlei Road", line: "9号线", city: "上海"),
        Station(name: "曹路", nameEn: "Caolu", line: "9号线", city: "上海"),

        // 10号线
        Station(name: "虹桥火车站", nameEn: "Hongqiao Railway Station", line: "10号线", city: "上海"),
        Station(name: "虹桥2号航站楼", nameEn: "Hongqiao Airport Terminal 2", line: "10号线", city: "上海"),
        Station(name: "虹桥1号航站楼", nameEn: "Hongqiao Airport Terminal 1", line: "10号线", city: "上海"),
        Station(name: "上海动物园", nameEn: "Shanghai Zoo", line: "10号线", city: "上海"),
        Station(name: "龙溪路", nameEn: "Longxi Road", line: "10号线", city: "上海"),
        Station(name: "水城路", nameEn: "Shuicheng Road", line: "10号线", city: "上海"),
        Station(name: "伊犁路", nameEn: "Yili Road", line: "10号线", city: "上海"),
        Station(name: "宋园路", nameEn: "Songyuan Road", line: "10号线", city: "上海"),
        Station(name: "虹桥路", nameEn: "Hongqiao Road", line: "10号线", city: "上海"),
        Station(name: "交通大学", nameEn: "Jiaotong University", line: "10号线", city: "上海"),
        Station(name: "上海图书馆", nameEn: "Shanghai Library", line: "10号线", city: "上海"),
        Station(name: "陕西南路", nameEn: "South Shaanxi Road", line: "10号线", city: "上海"),
        Station(name: "一大会址·新天地", nameEn: "Site of the First CPC National Congress · Xintiandi", line: "10号线", city: "上海"),
        Station(name: "老西门", nameEn: "Laoximen", line: "10号线", city: "上海"),
        Station(name: "豫园", nameEn: "Yu Garden", line: "10号线", city: "上海"),
        Station(name: "南京东路", nameEn: "East Nanjing Road", line: "10号线", city: "上海"),
        Station(name: "天潼路", nameEn: "Tiantong Road", line: "10号线", city: "上海"),
        Station(name: "四川北路", nameEn: "North Sichuan Road", line: "10号线", city: "上海"),
        Station(name: "海伦路", nameEn: "Hailun Road", line: "10号线", city: "上海"),
        Station(name: "邮电新村", nameEn: "Youdian Xincun", line: "10号线", city: "上海"),
        Station(name: "四平路", nameEn: "Siping Road", line: "10号线", city: "上海"),
        Station(name: "同济大学", nameEn: "Tongji University", line: "10号线", city: "上海"),
        Station(name: "国权路", nameEn: "Guoquan Road", line: "10号线", city: "上海"),
        Station(name: "五角场", nameEn: "Wujiaochang", line: "10号线", city: "上海"),
        Station(name: "江湾体育场", nameEn: "Jiangwan Stadium", line: "10号线", city: "上海"),
        Station(name: "三门路", nameEn: "Sanmen Road", line: "10号线", city: "上海"),
        Station(name: "三林路", nameEn: "Sanlin Road", line: "10号线", city: "上海"), // 修正: 三门路
        Station(name: "殷高东路", nameEn: "East Yingao Road", line: "10号线", city: "上海"),
        Station(name: "新江湾城", nameEn: "Xinjiangwancheng", line: "10号线", city: "上海"),
        Station(name: "国帆路", nameEn: "Guofan Road", line: "10号线", city: "上海"),
        Station(name: "双江路", nameEn: "Shuangjiang Road", line: "10号线", city: "上海"),
        Station(name: "高桥西", nameEn: "Gaoqiao West", line: "10号线", city: "上海"),
        Station(name: "高桥", nameEn: "Gaoqiao", line: "10号线", city: "上海"),
        Station(name: "港城路", nameEn: "Gangcheng Road", line: "10号线", city: "上海"),
        Station(name: "基隆路", nameEn: "Jilong Road", line: "10号线", city: "上海"),

        // 11号线
        Station(name: "迪士尼", nameEn: "Disney Resort", line: "11号线", city: "上海"),
        Station(name: "康新公路", nameEn: "Kangxin Highway", line: "11号线", city: "上海"),
        Station(name: "秀沿路", nameEn: "Xiuyan Road", line: "11号线", city: "上海"),
        Station(name: "罗山路", nameEn: "Luoshan Road", line: "11号线", city: "上海"),
        Station(name: "御桥", nameEn: "Yuqiao", line: "11号线", city: "上海"),
        Station(name: "浦三路", nameEn: "Pusan Road", line: "11号线", city: "上海"),
        Station(name: "三林", nameEn: "Sanlin", line: "11号线", city: "上海"),
        Station(name: "东方体育中心", nameEn: "Oriental Sports Center", line: "11号线", city: "上海"),
        Station(name: "龙耀路", nameEn: "Longyao Road", line: "11号线", city: "上海"),
        Station(name: "云锦路", nameEn: "Yunjin Road", line: "11号线", city: "上海"),
        Station(name: "龙华", nameEn: "Longhua", line: "11号线", city: "上海"),
        Station(name: "上海游泳馆", nameEn: "Shanghai Swimming Center", line: "11号线", city: "上海"),
        Station(name: "徐家汇", nameEn: "Xujiahui", line: "11号线", city: "上海"),
        Station(name: "交通大学", nameEn: "Jiaotong University", line: "11号线", city: "上海"),
        Station(name: "江苏路", nameEn: "Jiangsu Road", line: "11号线", city: "上海"),
        Station(name: "隆德路", nameEn: "Longde Road", line: "11号线", city: "上海"),
        Station(name: "曹杨路", nameEn: "Caoyang Road", line: "11号线", city: "上海"),
        Station(name: "真如", nameEn: "Zhenru", line: "11号线", city: "上海"),
        Station(name: "上海西站", nameEn: "Shanghai West Railway Station", line: "11号线", city: "上海"),
        Station(name: "南翔", nameEn: "Nanxiang", line: "11号线", city: "上海"),
        Station(name: "马陆", nameEn: "Malu", line: "11号线", city: "上海"),
        Station(name: "嘉定新城", nameEn: "Jiading Xincheng", line: "11号线", city: "上海"),
        Station(name: "安亭", nameEn: "Anting", line: "11号线", city: "上海"),
        Station(name: "花桥", nameEn: "Huaqiao", line: "11号线", city: "上海"),
        Station(name: "嘉定北", nameEn: "Jiading North", line: "11号线", city: "上海"),

        // 12号线
        Station(name: "金海路", nameEn: "Jinhai Road", line: "12号线", city: "上海"),
        Station(name: "申江路", nameEn: "Shenjiang Road", line: "12号线", city: "上海"),
        Station(name: "金京路", nameEn: "Jinjing Road", line: "12号线", city: "上海"),
        Station(name: "杨高北路", nameEn: "North Yanggao Road", line: "12号线", city: "上海"),
        Station(name: "巨峰路", nameEn: "Jufeng Road", line: "12号线", city: "上海"),
        Station(name: "东陆路", nameEn: "Donglu Road", line: "12号线", city: "上海"),
        Station(name: "宁国路", nameEn: "Ningguo Road", line: "12号线", city: "上海"),
        Station(name: "大连路", nameEn: "Dalian Road", line: "12号线", city: "上海"),
        Station(name: "提篮桥", nameEn: "Tilanqiao", line: "12号线", city: "上海"),
        Station(name: "国际客运中心", nameEn: "International Cruise Terminal", line: "12号线", city: "上海"),
        Station(name: "天潼路", nameEn: "Tiantong Road", line: "12号线", city: "上海"),
        Station(name: "曲阜路", nameEn: "Qufu Road", line: "12号线", city: "上海"),
        Station(name: "汉中路", nameEn: "Hanzhong Road", line: "12号线", city: "上海"),
        Station(name: "南京西路", nameEn: "West Nanjing Road", line: "12号线", city: "上海"),
        Station(name: "陕西南路", nameEn: "South Shaanxi Road", line: "12号线", city: "上海"),
        Station(name: "嘉善路", nameEn: "Jiashan Road", line: "12号线", city: "上海"),
        Station(name: "大木桥路", nameEn: "Damuqiao Road", line: "12号线", city: "上海"),
        Station(name: "龙华中路", nameEn: "Middle Longhua Road", line: "12号线", city: "上海"),
        Station(name: "龙华", nameEn: "Longhua", line: "12号线", city: "上海"),
        Station(name: "龙漕路", nameEn: "Longcao Road", line: "12号线", city: "上海"),
        Station(name: "漕宝路", nameEn: "Caobao Road", line: "12号线", city: "上海"),
        Station(name: "桂林公园", nameEn: "Guilin Park", line: "12号线", city: "上海"),
        Station(name: "虹莘路", nameEn: "Hongxin Road", line: "12号线", city: "上海"),
        Station(name: "七莘路", nameEn: "Qixin Road", line: "12号线", city: "上海"),

        // 13号线
        Station(name: "金运路", nameEn: "Jinyun Road", line: "13号线", city: "上海"),
        Station(name: "金沙江西路", nameEn: "West Jinshajiang Road", line: "13号线", city: "上海"),
        Station(name: "丰庄", nameEn: "Fengzhuang", line: "13号线", city: "上海"),
        Station(name: "祁连山南路", nameEn: "South Qilianshan Road", line: "13号线", city: "上海"),
        Station(name: "真北路", nameEn: "Zhenbei Road", line: "13号线", city: "上海"),
        Station(name: "大渡河路", nameEn: "Daduhe Road", line: "13号线", city: "上海"),
        Station(name: "金沙江路", nameEn: "Jinshajiang Road", line: "13号线", city: "上海"),
        Station(name: "隆德路", nameEn: "Longde Road", line: "13号线", city: "上海"),
        Station(name: "武宁路", nameEn: "Wuning Road", line: "13号线", city: "上海"),
        Station(name: "长寿路", nameEn: "Changshou Road", line: "13号线", city: "上海"),
        Station(name: "江宁路", nameEn: "Jiangning Road", line: "13号线", city: "上海"),
        Station(name: "汉中路", nameEn: "Hanzhong Road", line: "13号线", city: "上海"),
        Station(name: "自然博物馆", nameEn: "Shanghai Natural History Museum", line: "13号线", city: "上海"),
        Station(name: "南京西路", nameEn: "West Nanjing Road", line: "13号线", city: "上海"),
        Station(name: "淮海中路", nameEn: "Middle Huaihai Road", line: "13号线", city: "上海"),
        Station(name: "一大会址·新天地", nameEn: "Site of the First CPC National Congress · Xintiandi", line: "13号线", city: "上海"),
        Station(name: "马当路", nameEn: "Madang Road", line: "13号线", city: "上海"),
        Station(name: "世博会博物馆", nameEn: "World Expo Museum", line: "13号线", city: "上海"),
        Station(name: "世博大道", nameEn: "Shibo Avenue", line: "13号线", city: "上海"),
        Station(name: "中科路", nameEn: "Zhongke Road", line: "13号线", city: "上海"),
        Station(name: "张江路", nameEn: "Zhangjiang Road", line: "13号线", city: "上海"),

        // 14号线
        Station(name: "封浜", nameEn: "Fengbang", line: "14号线", city: "上海"),
        Station(name: "真如", nameEn: "Zhenru", line: "14号线", city: "上海"),
        Station(name: "武宁路", nameEn: "Wuning Road", line: "14号线", city: "上海"),
        Station(name: "静安寺", nameEn: "Jing'an Temple", line: "14号线", city: "上海"),
        Station(name: "陆家嘴", nameEn: "Lujiazui", line: "14号线", city: "上海"),
        Station(name: "豫园", nameEn: "Yu Garden", line: "14号线", city: "上海"),
        Station(name: "一大会址·黄陂南路", nameEn: "Site of the First CPC National Congress · South Huangpi Road", line: "14号线", city: "上海"),
        Station(name: "浦东大道", nameEn: "Pudong Avenue", line: "14号线", city: "上海"),
        Station(name: "蓝天路", nameEn: "Lantian Road", line: "14号线", city: "上海"),
        Station(name: "桂桥路", nameEn: "Guiqiao Road", line: "14号线", city: "上海"),

        // 15号线
        Station(name: "顾村公园", nameEn: "Gucun Park", line: "15号线", city: "上海"),
        Station(name: "上海西站", nameEn: "Shanghai West Railway Station", line: "15号线", city: "上海"),
        Station(name: "大渡河路", nameEn: "Daduhe Road", line: "15号线", city: "上海"),
        Station(name: "娄山关路", nameEn: "Loushanguan Road", line: "15号线", city: "上海"),
        Station(name: "桂林路", nameEn: "Guilin Road", line: "15号线", city: "上海"),
        Station(name: "上海南站", nameEn: "Shanghai South Railway Station", line: "15号线", city: "上海"),
        Station(name: "景洪路", nameEn: "Jinghong Road", line: "15号线", city: "上海"),
        Station(name: "紫竹高新区", nameEn: "Zizhu Hi-tech Zone", line: "15号线", city: "上海"),

        // 16号线
        Station(name: "龙阳路", nameEn: "Longyang Road", line: "16号线", city: "上海"),
        Station(name: "华夏中路", nameEn: "Middle Huaxia Road", line: "16号线", city: "上海"),
        Station(name: "罗山路", nameEn: "Luoshan Road", line: "16号线", city: "上海"),
        Station(name: "野生动物园", nameEn: "Shanghai Wild Animal Park", line: "16号线", city: "上海"),
        Station(name: "惠南", nameEn: "Huinan", line: "16号线", city: "上海"),
        Station(name: "临港大道", nameEn: "Lingang Avenue", line: "16号线", city: "上海"),
        Station(name: "滴水湖", nameEn: "Dishui Lake", line: "16号线", city: "上海"),

        // 17号线
        Station(name: "虹桥火车站", nameEn: "Hongqiao Railway Station", line: "17号线", city: "上海"),
        Station(name: "国家会展中心", nameEn: "National Exhibition and Convention Center", line: "17号线", city: "上海"),
        Station(name: "朱家角", nameEn: "Zhujiajiao", line: "17号线", city: "上海"),
        Station(name: "东方绿舟", nameEn: "Oriental Land", line: "17号线", city: "上海"),
        Station(name: "西岑", nameEn: "Xicen", line: "17号线", city: "上海"),

        // 18号线
        Station(name: "康文路", nameEn: "Kangwen Road", line: "18号线", city: "上海"),
        Station(name: "呼兰路", nameEn: "Hulan Road", line: "18号线", city: "上海"),
        Station(name: "长江南路", nameEn: "South Changjiang Road", line: "18号线", city: "上海"),
        Station(name: "复旦大学", nameEn: "Fudan University", line: "18号线", city: "上海"),
        Station(name: "国权路", nameEn: "Guoquan Road", line: "18号线", city: "上海"),
        Station(name: "江浦路", nameEn: "Jiangpu Road", line: "18号线", city: "上海"),
        Station(name: "昌邑路", nameEn: "Changyi Road", line: "18号线", city: "上海"),
        Station(name: "民生路", nameEn: "Minsheng Road", line: "18号线", city: "上海"),
        Station(name: "龙阳路", nameEn: "Longyang Road", line: "18号线", city: "上海"),
        Station(name: "御桥", nameEn: "Yuqiao", line: "18号线", city: "上海"),
        Station(name: "航头", nameEn: "Hangtou", line: "18号线", city: "上海"),

        // 浦江线
        Station(name: "沈杜公路", nameEn: "Shendu Highway", line: "浦江线", city: "上海"),
        Station(name: "三鲁公路", nameEn: "Sanlu Highway", line: "浦江线", city: "上海"),
        Station(name: "闵瑞路", nameEn: "Minrui Road", line: "浦江线", city: "上海"),
        Station(name: "浦航路", nameEn: "Puhang Road", line: "浦江线", city: "上海"),
        Station(name: "东城一路", nameEn: "Dongcheng 1st Road", line: "浦江线", city: "上海"),
        Station(name: "汇臻路", nameEn: "Huizhen Road", line: "浦江线", city: "上海"),

        // 磁浮线
        Station(name: "龙阳路", nameEn: "Longyang Road", line: "磁浮线", city: "上海"),
        Station(name: "浦东国际机场", nameEn: "Pudong International Airport", line: "磁浮线", city: "上海")
    ]
}
